<h1>Quel est le rapport entre censure, liberté sur Internet et dans le monde réel?</h1>
<p class="chapa">Quand on parle de censure ou de liberté sur Internet, on fait référence à son impact sur le monde réel. En quoi Internet a un impact sur la liberté des citoyens d’un pays? Existe-t-il des cas où la liberté sur Internet et dans la vie quotidienne entrent en contradiction ? Quel est le rapport entre censure, liberté sur Internet et dans le monde réel ?</p>
<img id="illustration" src="./style/image/illustration/bigbrother.jpg" alt="big brother is watching you"/>
<h2>Internet, un outil de privation de liberté puissant</h2>
<p>Internet est un outil puissant de privation de libertés réelles utilisé par nombre de régimes autoritaires.</p>
<h3>Liberté d’expression</h3>
<p>La liberté d’expression est la plus menacée. Il est en effet très facile de faire taire les opinions dissidentes sur Internet en n’autorisant l’accès au peuple qu’aux sources d’information contrôlées par le gouvernement via la mise en place de whitelists ou la cyberattaque systématique des médias indépendants et en censurant tout contenu contrevenant au pouvoir sur les réseaux sociaux.

Des ONG comme Freedom House luttent contre la cyber censure exercée dans un peu plus de 48 pays dans le monde, dont la Chine qui est le pays où la cyber censure est la plus présente avec un peu plus de 3000 sites internet bloqués en à peine 3 ans, sans compter toutes les applications de messagerie instantanée et les réseaux sociaux comme Facebook, Twitter et YouTube. 

La Chine décide alors de mettre en place un intranet géant à l’échelle nationale permettant de contrôler toutes les informations circulant sur internet. Cela permet aussi au pays de diffuser sa propagande pour le gouvernement. Elle justifie ses actions en disant que c’est pour le bien du peuple, pour les protéger des mauvaises influences extérieures (religion, terrorisme, pornographie, …).

Les utilisateurs Chinois ne respectant pas les conditions imposées par le pays, peuvent se voir arrêtés par la police chinoise de l’internet et être condamnés entre 8 à 10 ans de prison pour avoir divulgué de fausses rumeurs, s’être moqué d’un membre du gouvernement ou bien même en postant un simple emoji sur les réseaux sociaux locaux.
Mais certains de ces utilisateurs arrivent tout de même à passer entre les mailles du filet et à réussir à accéder à internet sans les contraintes imposées par le gouvernement chinois.</p>
<h3>Désinformation</h3>
<p>Beaucoup de responsables de pays comme ceux de la Chine ou de la Russie contrôlent et surveillent plus sévèrement les médias à contenu politique en ligne pour pouvoir exercer une meilleur propagande peu avant leurs élections. Ces pratiques vont complètement à l’encontre aux Droits de l’Homme surtout par rapport à la liberté d’expressions mais aussi à la religion et la communauté LGBTQ, sont mis en place (suppression de l’anonymat en ligne ou de contenu en ligne). Ils essayent de promulguer certains idéaux politique en faisant appel également à de “fake news”.
Mais ce ne sont pas les pays où il y a le plus de censure qui ont des pratiques douteuse: en France par exemple, il y a depuis 2015 le DNS menteur qui consiste à afficher l’erreur 404 ou une page nous indiquant que la page n’existe pas, or elle existe mais elle a été supprimer dans notre pays. Ce procédé est d’autant plus douteux que l’Etat nous a fournit aucune information sur les sites ayant été censurés et les raisons de cette censure.</p>
<h3>Autocensure</h3>
<p>Dans certains pays, souvent ceux qui sont en conflit, les citoyens ont peur de leur gouvernement, car ceux-ci leur instaure une pression pour ne rien divulguer. Ces personnes, ayant peur des revendications, évite de s’exprimer librement sur internet.

Internet est donc une variable sur laquelle les gouvernements peuvent jouer pour limiter les libertés de ses habitants.</p>
<h2>Contradiction entre les libertés</h2>
<p>Mais si Internet est un outil de privation de liberté puissant, trop de libertés sur Internet peut entrer en contradiction avec les autres formes de liberté. C’est cet autre extrême que nous allons étudier.</p>
<h3>Sécurité et confidentialité</h3>
<p>Un cas étonnant d’atteinte à la liberté sur Internet nous vient du pays accueillant la Statue de la Liberté, les Etats-Unis d’Amérique : bien qu’il soit symbole de liberté, ses services de renseignements sont à la base du plus grand scandale du siècle en terme d’espionnage sur Internet.
Il s’agit du programme d’espionnage américain de la NSA, dévoilé par Edward Snowden en 2013, qui consistait en la récupération et en la centralisation des données personnelles de millions de citoyens. Bien qu'il n'y ai pas de notion de censure, c'est une atteinte très grave à la vie privée des citoyens, qui est une liberté fondamentale.
Malgré la gravité de l’affaire, les Etats-Unis ont toujours crié haut et fort avoir mis en place un tel dispositif pour protéger les citoyens américains suite aux attentats de 2001, donc pour leur sécurité - par extension leur liberté de s’épanouir dans un pays prospère -, c’est là un dilemme déontologique.
La France aussi fait partie de la danse, en ayant censuré nombre de publications sur Internet dans le cadre du plan vigipirate faisant suite aux attentats de Charlie Hebdo puis du 13 novembre comme nous l’indique le rapport de l’ONG Freedom House de 2017 portant sur la liberté d’Internet dans le monde.
L’Etat justifie ces actes là par la menace terroriste de ces dernières années. Une contradiction entre liberté sur Internet et sécurité existe donc. Rappelons que la sécurité est à la base de toutes libertés au sein d’un pays, notamment en France comme l’a écrit Rousseau à l’aube de la République Française indivisible dans son essai Du Contrat Social.</p>
<h3>Internet et économie libérale</h3>
<p>La censure sur Internet dans les pays libres se retrouve également dans les nombreuses atteintes à la neutralité du net. En effet, pays libre rime souvent avec économie libérale, donc fournisseurs d’accès Internet (dits FAI) privés et possibles conflits d'intérêts. Nous avons un exemple français de ce genre de conflits : Orange, en 2015, a empêché l’accès à T411 - un site de téléchargement en peer-to-peer- à ses abonnés en utilisant la technique dite du DNS menteur. Le serveur DNS est ce qui permet de convertir une adresse web en adresse IP pour contacter le serveur du site en question et en obtenir la page web. Un DNS menteur est simplement un serveur DNS qui convertit une adresse web en la mauvaise adresse IP pour empêcher l’accès au site web ciblé. Sachant que T411 est connu pour permettre le téléchargement gratuit de films et de séries que l'on peut acheter en vidéo à la demande sur les box Orange, le conflit d'intérêt est évident. On voit donc une contradiction entre la liberté sur le plan commercial et la liberté sur Internet.</p>
<p>En conclusion, censure et liberté sur Internet sont étroitement liés à la liberté réelle, et pour trouver un optimum de liberté, il est parfois nécessaire de faire des concessions : de trouver un combinaison équilibrée entre liberté sur Internet et liberté réelle.</p>

<p id="source">Sources :</p>