<h1>La réputation d'un pays en terme de liberté est-elle nécessairement vérifiée sur Internet ?</h1>
<img id="miniature" type="hidden" src="./style/image/illustration/mapfreedom_thumb_smaller.png" alt="Map freedomhouse"/>
<p>Quand on parle de censure et de privation de libertés sur Internet, on a tendance à évoquer des dictatures ou régimes que l’on qualifierait d’autoritaires comme la Chine, la Corée du Nord, ou la Russie.
Mais qu’en est-il des pays qui clament être libres comme les Etats-Unis ou la France ? Sont-ils si exemplaires en terme de libertés sur Internet ? La réputation d’un pays en terme de liberté est-elle nécessairement vérifiée sur Internet ?</p>
<img id="illustration" src="./style/image/illustration/mapfreedom.jpg" alt="Map freedomhouse"/>
<h2>Chapavoler</h2>
<p>Les pays où Internet est le moins libre sont évidemment ceux où la liberté d’expression est la plus restreinte. Il est en effet très facile de faire taire les opinions dissidentes sur Internet en n’autorisant l’accès au peuple qu’aux sources d’information contrôlées par le gouvernement via la mise en place de whitelists ou la cyberattaque systématique des médias indépendants et en censurant tout contenu contrevenant au pouvoir sur les réseaux sociaux. La Chine a par exemple fermé 13 000 sites web depuis 2015 et 10 millions de comptes sur les réseaux sociaux (réseaux exclusivement chinois).</p>
<p>La censure virtuelle peut d’ailleurs se poursuivre dans la vie réelle, par le biais de lourdes sanctions, surtout quand il s’agit de dissidents ou de ceux qui permettent de contourner la censure. On peut citer le cas du tribunal de Guangxi qui a condamné un homme à 5 ans et demi de prison parce qu’il vendait des VPN (Virtual Private Network) qui permettent de passer outre les blocages et simulant une connexion dans un autre pays.</p>
<p>Les stratégies de contrôle d’Internet sont aussi variées. Certains pays souhaitent contrôler Internet subtilement, et ainsi donner une illusion de liberté au peuple, comme la Russie, alors que d’autres pays comme la Chine bloquent purement et simplement les sources d’information difficilement contrôlables comme les réseaux sociaux “internationaux” tel facebook, nous indique l’ONG Freedom House dans un rapport de 2017.</p>
<p>Il y a donc une certaine cohérence entre la réputation d’un pays et l’état de son réseau.</p>
<h2>Et bim</h2>
<p>Toutefois, il existe des cas de privation de libertés sur Internet plus étonnants. On peut citer pour commencer le pays accueillant la Statue de la Liberté, les Etats-Unis d’Amérique : bien qu’il soit symbole de liberté, ses services de renseignements sont à la base du plus grand scandale du siècle en terme d’espionnage sur Internet.</p>
<p>Il s’agit du programme d’espionnage américain de la NSA, dévoilé par Edward Snowden en 2013, qui consistait en la récupération et en la centralisation des données personnelles de millions de citoyens. Bien qu'il n'y ai pas de notion de censure, c'est une atteinte très grave à la vie privée des citoyens, qui est une liberté fondamentale. </p>
<p>La censure sur Internet dans les pays libres se retrouve également dans les nombreuses atteintes à la neutralité du net. En effet, pays libre rime souvent avec économie libérale, donc fournisseurs d’accès Internet (dits FAI) privés et possibles conflits d'intérêts. Nous avons un exemple français de ce genre de conflits : Orange, en 2015, a empêché l’accès à T411 - un site de téléchargement en peer-to-peer- à ses abonnés en utilisant la technique dite du DNS menteur. Le serveur DNS est ce qui permet de convertir une adresse web en adresse IP pour contacter le serveur du site en question et obtenir la page web. Un DNS menteur est simplement un serveur DNS qui convertit une adresse web en la mauvaise adresse IP pour empêcher l’accès au site web ciblé. Sachant que T411 est connu pour permettre le téléchargement gratuit de films et de séries que l'on peut acheter en vidéo à la demande sur les box Orange, le conflit d'intérêt est évident. On voit donc une contradiction entre la liberté sur le plan commercial et la liberté sur Internet.</p>
<p>Le rapport de Freedom House de 2017 nous indique également un recul de la liberté d’expression sur Internet dans les pays libres notamment en France où de nombreux cas de censures ont été recensés dans le cadre du plan vigipirate faisant suite aux attentats de Charlie Hebdo puis du 13 novembre. L’Etat justifie ces actes là par la menace terroriste de ces dernières années. Une contradiction entre liberté sur Internet et sécurité existe donc.
Comme vu ci-dessus, il existe des cas de censure et d’atteintes à la liberté sur Internet dans les pays réputés les plus libres contrairement à ce que l’on pourrait traditionnellement croire.<br/><br/></p>


<p>Finalement, on peut distinguer les cas où la privation de liberté sur Internet s’inscrit dans une logique autoritaire voire totalitaire, et les cas où les atteintes à la liberté sur Internet sont les conséquences d’autres principes en vigueur dans les pays libres comme la libéralisation économique ou la sécurité intérieure (par extension les renseignements).</p>

<p id="source">Sources :</p>